#!/bin/bash
# Fedora Utils lets you install codecs and additional software,
# fix problems, tweak and cleanup your system,
# view system information and much more with just few clicks.
#
# Copyright (C) 2012  Satyajit sahoo
#
# License: GNU GPLv3 <http://www.gnu.org/licenses/gpl-3.0.html>
# Author: Satyajit Sahoo <satyajit.happy@gmail.com>
# Code: GitHub <https://github.com/satya164/fedorautils>

# Declare variables
program="Fedora Utils"
version="2.3.2"
user=`who | grep $(echo "$DISPLAY" | cut -d '.' -f 1) | cut -d ' ' -f 1 | tail -1`
errors="0"
homedir=`awk -F: -v v="$user" '{if ($1==v) print $6}' /etc/passwd`
scriptdir=`cd $(dirname "${BASH_SOURCE[0]}") && pwd`

# Default configuration
libdir="$scriptdir/lib"			# Provides core functionality, change only if you know what are you doing
moduledir="$scriptdir/modules"		# Provides the main menu module
plugindir="$scriptdir/plugins"		# The directory where are containing all the plugins
supportdir="$scriptdir/support"		# Contains files representing supported distros
workingdir="/tmp/fedorautils"		# A temporary directory where everything is done, automatically created as needed
sysconf="/etc/fedorautilsrc"		# System wide configuration file for fedorautils
userconf="$homedir/.fedorautilsrc"	# User specific configuration file for fedorautils
lockfile="/var/run/fedorautils.pid"	# The lockfile used to prevent running of multiple instances
logfile="/var/log/fedorautils.log"	# Outputs will be redirected to this file if logging is enabled
enablelog="yes"				# If you want to disable logging, change "yes" to "no"
logmode="default"			# Change "default" to "buffer" to buffer logging and keep previous log
downagent="curl"			# To use wget instead of curl unless preferred, change "curl" to "wget"
prefwget="yes"				# If you prefer curl over wget, change "yes" to "no"
forcedown="no"				# If you want to force redownload of files, change "no" to "yes"
forcedistro="no"			# If you want to run the script with unsupported distro, change "no" to "yes"
keepbackup="yes"			# If you don't want to backup previous configurations, change "yes" to "no"
keepdownloads="yes"			# If you don't intend to save downloads, change "yes" to "no"
downloadsdir="$homedir/fedorautils_dl"	# All downloaded files are saved in this directory
tts="no"				# If you want fedorautils to speak, change "no" to "yes"

# Set Colors
BOLD="\033[1;10m"
RED="\033[0;31m"
REDBOLD="\033[1;31m"
GREEN="\033[0;32m"
GREENBOLD="\033[1;32m"
YELLOW="\033[0;33m"
YELLOWBOLD="\033[1;33m"
BLUE="\033[0;34m"
BLUEBOLD="\033[1;34m"
ENDCOLOR="\033[0m"

# Source libraries
SAVEIFS="$IFS"
IFS="
"
for lib in $libdir/*.sh; do source "$lib"; done
IFS="$SAVEIFS"

# Source config files if present
[[ -f "$sysconf" ]] && source "$sysconf"
[[ -f "$userconf" ]] && source "$userconf"

# Additional parameters
trap terminate_program INT

# Run the program
check_args "$@"
show_license
check_root "$@"
enable_log
check_lock
check_req
initialize_program
show_update &
ui_main
complete_program

# Please report bugs at <http://github.com/satya164/fedorautils/issues>
# End of the Script
