#!/bin/bash
# Fedora Utils lets you install codecs and additional software,
# fix problems, tweak and cleanup your system,
# view system information and much more with just few clicks.
#
# Copyright (C) 2012  Satyajit sahoo
#
# License: GNU General Public License 3 <http://www.gnu.org/licenses/gpl-3.0.html>
# Author: Satyajit Sahoo <satyajit.happy@gmail.com>
# Site: Project Page <http://fedorautils.sorceforge.net>
#
# This script benefits both for codes and ideas from
# AutoPlus by dangermouse <http://www.dnmouse.org/autoten/>
# easyLife by dulinux <http://easylifeproject.org>
#
# I'm grateful to dangermouse for providing RPM pacakge and pointing out the bugs & mistakes
# Thanks to Andrew <http://webupd8.org> for testing and publishing it in his blog
# Special credits to Valdur Kana <valdur55@gmail.com> for dynamic way of creating menus
# And of course, all those users who reported bugs

# Declare variables

program="Fedora Utils"
version="Experimental"
user="$(logname)"
errors="0"
homedir=`awk -F: -v v="$(logname)" '{if ($1==v) print $6}' /etc/passwd`
scriptdir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default configuration

libdir="$scriptdir/lib"			# Provides core functionality, change only if you know what are you doing
moduledir="$scriptdir/modules"		# Provides the main menu module
plugindir="$scriptdir/plugins"		# The directory where are containing all the plugins
bindir="$scriptdir/bin"			# Contains binary executables
workingdir="/tmp/fedorautils"		# A temporary directory where everything is done, automatically created as needed
sysconf="/etc/fedorautilsrc"		# System wide configuration file for fedorautils
userconf="$homedir/.fedorautilsrc"	# User specific configuration file for fedorautils
lockfile="/var/run/fedorautils.pid"	# The lockfile used to prevent running of multiple instances
logfile="/var/log/fedorautils.log"	# Outputs will be redirected to this file if logging is enabled
keeplog="no"				# If you want to enable logging, change "no" to "yes"
downagent="curl"			# To use wget instead of curl unless preferred, change "curl" to "wget"
prefwget="yes"				# If you prefer curl over wget, change "yes" to "no"
forcedown="no"				# If you want to force redownload of files, change "no" to "yes"
forcedistro="no"			# If you want to run the script with unsupported distro, change "no" to "yes"
keepbackup="yes"			# If you don't want to backup previous configurations, change "yes" to "no"
keepdownloads="no"			# If you don't intend to save downloads, change "yes" to "no"
downloadsdir="$homedir/fedorautils_dl"	# All downloaded files are saved in this directory
tts="no"				# If you want fedorautils to speak, change "no" to "yes"

# Set Colors

BOLD="\033[1;10m"
RED="\033[0;31m"
REDBOLD="\033[1;31m"
GREEN="\033[0;32m"
GREENBOLD="\033[1;32m"
YELLOW="\033[0;33m"
YELLOWBOLD="\033[1;33m"
BLUE="\033[0;34m"
BLUEBOLD="\033[1;34m"
ENDCOLOR="\033[0m"

# Source libraries

for lib in $libdir/*.sh; do source "$lib"; done

# Source binaries

if [ -d "$bindir" ]; then
	export PATH="$bindir:$PATH"
fi

# Source config files if present

if [ -f "$sysconf" ]; then
	source "$sysconf"
fi
if [ -f "$userconf" ]; then
	source "$userconf"
fi

# Additional parameters

trap terminate_program INT

# Run the program

check_args "$@"
show_license
check_root "$@"
enable_log
check_lock
check_req
initialize_program
ui_main
complete_program

# Please report bugs at <http://github.com/satya164/fedorautils/issues>
# End of the Script
