#!/bin/bash
# Fedy lets you install codecs and additional software,
# fix problems, tweak and cleanup your system,
# view system information and much more with just few clicks.
#
# Copyright (C) 2014 Satyajit Sahoo
#
# License: GNU GPLv3 <http://www.gnu.org/licenses/gpl-3.0.html>
# Author: Satyajit Sahoo <satyajit.happy@gmail.com>
# Code: GitHub <https://github.com/satya164/fedy>

# Declare variables
program="Fedy"
unixname="fedy"
version="3.2.2"
user=`who | grep $(echo "$DISPLAY" | cut -d '.' -f 1) | cut -d ' ' -f 1 | tail -1`
errors="0"
homedir=`awk -F: -v v="$user" '{if ($1==v) print $6}' /etc/passwd`
scriptdir=`cd $(dirname "${BASH_SOURCE[0]}") && pwd`

# Default configuration
libdir="$scriptdir/lib"         # Provides core functionality, change only if you know what are you doing
rundir="$scriptdir/run"         # Contains scripts to run at startup
moduledir="$scriptdir/modules"  # Provides the main menu module
plugindir="$scriptdir/plugins"  # The directory where are containing all the plugins
workingdir="/tmp/fedy"          # A temporary directory where everything is done, automatically created as needed
sysconf="/etc/fedyrc"           # System wide configuration file for fedy
userconf="$homedir/.fedyrc"     # User specific configuration file for fedy
lockfile="/var/run/fedy.pid"    # The lockfile used to prevent running of multiple instances
logfile="/var/log/fedy.log"     # Outputs will be redirected to this file if logging is enabled
enablelog="false"               # If you want to disable logging, change "true" to "false"
tryprevrel="true"               # If you don't want to try installing from repo of a previous release, change "true" to "false"
downagent="wget"                # To use curl to download files, change "wget" to "curl"
redownload="false"              # To force redownload of files, change "false" to "true"
forcedistro="false"             # To run the script with unsupported distro, change "false" to "true"
keepbackup="true"               # If you don't want to backup previous configurations, change "true" to "false"
keepdownloads="true"            # If you don't want to save downloads, change "true" to "false"
downloadsdir="$homedir/fedy_dl" # All downloaded files are saved in this directory

# Set Colors
BOLD="\033[1;10m"
RED="\033[0;31m"
REDBOLD="\033[1;31m"
GREEN="\033[0;32m"
GREENBOLD="\033[1;32m"
YELLOW="\033[0;33m"
YELLOWBOLD="\033[1;33m"
BLUE="\033[0;34m"
BLUEBOLD="\033[1;34m"
ENDCOLOR="\033[0m"

# Additional parameters
trap terminate_program INT

# Source config files if present
[[ -f "$sysconf" ]] && source "$sysconf"
[[ -f "$userconf" ]] && source "$userconf"

# Source libraries
while read lib; do
    source "$lib"
done < <(find "$libdir/" -name '*.sh' | sort -u)

# Run the program
while read run; do
    source "$run"
    runcommand=$(grep "# Run:" "$run" | sed -e 's/# Run: //')
    eval "$runcommand" "$@"
done < <(find "$rundir/" -name '*.sh' | sort -u)

# Please report bugs at <http://github.com/satya164/fedy/issues>
# End of the Script
